'''
default config

HIKARI_SERVER="HiKaRi_Server"
HIKARI_VERSION=-0.01
APP_NAME="HiKaRi_ServerCenter"

LOCALHOST="127.0.0.1"
HIKARI_PORT=5491

KILL_INTERVAL=30
KILL_INITIAL_VALUE=2
KILL_EVENT_VALUE=1
'''

HIKARI_SERVER="HiKaRi_Server"
HIKARI_VERSION=-0.01
APP_NAME="HiKaRi_ServerCenter"


LOCALHOST="127.0.0.1"
HIKARI_PORT=5491

KILL_INTERVAL=30
KILL_INITIAL_VALUE=2
KILL_EVENT_VALUE=1
